name: Deploy Quanto Theme via FTP

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  web-deploy:
    name: Deploy to Staging Server via FTP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Sync Files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: wp-content/themes/quanto/
          local-dir: ./quanto/
